global using BasicBlazorLibrary.Components.BaseClasses;
global using BasicBlazorLibrary.Components.Basic;
global using BasicBlazorLibrary.Helpers;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses; //so i can have access to the exceptions when needed.
global using CommonBasicLibraries.CollectionClasses;
global using Microsoft.AspNetCore.Components;
global using Microsoft.Extensions.DependencyInjection;
global using Phase14MVP2.Components;
global using bb1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using cc1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using css1 = BasicBlazorLibrary.CssHelpers.AllCssClasses; //so i can have intellisense completely from c# if i want.
global using ff1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using Phase14MVP2.Services.Crops;
global using Phase14MVP2.Services.Trees;
global using Phase14MVP2.Services.Animals;
global using Phase14MVP2.Services.Workshops;
global using Phase14MVP2.Services.Workers;
global using Phase14MVP2.Services.Worksites;
global using Phase14MVP2;
global using CommonBasicLibraries.BasicUIProcesses;
global using DocumentDbLibrary;
global using CommonBasicLibraries.DatabaseHelpers.AbstractStaticInterfaces;
global using dd1 = CommonBasicLibraries.DatabaseHelpers.MiscClasses.GlobalClass;
global using SQLiteHelperLibraries;
global using mm1 = Phase14MVP2.DataAccess.Core.MainDatabase;
global using Phase14MVP2.Quests;
global using Phase14MVP2.Services.Core;
global using Phase14MVP2.Services.Balance;
global using Phase14MVP2.Services.Inventory;
global using Phase14MVP2.DataAccess.Inventory;
global using Phase14MVP2.Utilities;
global using Phase14MVP2.Services.Upgrades;
global using Phase14MVP2.Services.Progression;
global using Phase14MVP2.Services.Catalog;
global using Phase14MVP2.Services.Store;
global using Phase14MVP2.Services.Items;
